export const mockData = {
  cpu: [
    {
      id: 1,
      nombre: "Intel Core i9-13900K",
      socket: "LGA1700",
      compatible_con: { Z690: true, Z790: true },
      precio: 599.99,
      imagen_url: "https://www.deffo.com.ar/wp-content/uploads/2020/09/Core-i9-10th-unlock-9.jpg",
    },
    {
      id: 2,
      nombre: "Intel Core i7-13700K",
      socket: "LGA1700",
      compatible_con: { Z690: true, Z790: true, B760: true },
      precio: 409.99,
      imagen_url: "https://www.deffo.com.ar/wp-content/uploads/2020/09/Core-i9-10th-unlock-9.jpg",
    },
    {
      id: 3,
      nombre: "Intel Core i5-13600K",
      socket: "LGA1700",
      compatible_con: { Z690: true, Z790: true, B760: true, H770: true },
      precio: 319.99,
      imagen_url: "https://www.deffo.com.ar/wp-content/uploads/2020/09/Core-i9-10th-unlock-9.jpg",
    },
    {
      id: 4,
      nombre: "AMD Ryzen 9 7950X",
      socket: "AM5",
      compatible_con: { X670E: true, X670: true, B650E: true },
      precio: 699.99,
      imagen_url: "https://m.media-amazon.com/images/I/5116zdA9uyL._AC_UF894,1000_QL80_.jpg",
    },
    {
      id: 5,
      nombre: "AMD Ryzen 7 7700X",
      socket: "AM5",
      compatible_con: { X670E: true, X670: true, B650E: true, B650: true },
      precio: 399.99,
      imagen_url: "https://m.media-amazon.com/images/I/5116zdA9uyL._AC_UF894,1000_QL80_.jpg",
    },
    {
      id: 6,
      nombre: "AMD Ryzen 5 7600X",
      socket: "AM5",
      compatible_con: { X670E: true, X670: true, B650E: true, B650: true, A620: true },
      precio: 299.99,
      imagen_url: "https://m.media-amazon.com/images/I/5116zdA9uyL._AC_UF894,1000_QL80_.jpg",
    },
  ],
  gpu: [
    {
      id: 1,
      nombre: "NVIDIA GeForce RTX 4090",
      tamano_gpu: "336",
      watts: 450,
      precio: 1599.99,
      imagen_url: "https://m.media-amazon.com/images/I/81KR0fO8WgL._AC_SL1500_.jpg",
    },
    {
      id: 2,
      nombre: "NVIDIA GeForce RTX 4080",
      tamano_gpu: "304",
      watts: 320,
      precio: 1199.99,
      imagen_url: "https://m.media-amazon.com/images/I/81KR0fO8WgL._AC_SL1500_.jpg",
    },
    {
      id: 3,
      nombre: "NVIDIA GeForce RTX 4070 Ti",
      tamano_gpu: "285",
      watts: 285,
      precio: 799.99,
      imagen_url: "https://m.media-amazon.com/images/I/81KR0fO8WgL._AC_SL1500_.jpg",
    },
    {
      id: 4,
      nombre: "AMD Radeon RX 7900 XTX",
      tamano_gpu: "287",
      watts: 355,
      precio: 999.99,
      imagen_url: "https://m.media-amazon.com/images/I/81KR0fO8WgL._AC_SL1500_.jpg",
    },
    {
      id: 5,
      nombre: "AMD Radeon RX 7900 XT",
      tamano_gpu: "276",
      watts: 300,
      precio: 899.99,
      imagen_url: "https://m.media-amazon.com/images/I/81KR0fO8WgL._AC_SL1500_.jpg",
    },
    {
      id: 6,
      nombre: "AMD Radeon RX 7800 XT",
      tamano_gpu: "267",
      watts: 263,
      precio: 499.99,
      imagen_url: "https://m.media-amazon.com/images/I/81KR0fO8WgL._AC_SL1500_.jpg",
    },
  ],
  ram: [
    {
      id: 1,
      nombre: "Corsair Vengeance RGB Pro 32GB",
      tipo_memoria: "DDR4",
      capacidad_gb: 32,
      precio: 129.99,
      imagen_url: "https://m.media-amazon.com/images/I/81prSLYZ8XL.jpg",
    },
    {
      id: 2,
      nombre: "G.Skill Trident Z RGB 16GB",
      tipo_memoria: "DDR4",
      capacidad_gb: 16,
      precio: 89.99,
      imagen_url: "https://m.media-amazon.com/images/I/81prSLYZ8XL.jpg",
    },
    {
      id: 3,
      nombre: "Kingston FURY Beast 32GB",
      tipo_memoria: "DDR4",
      capacidad_gb: 32,
      precio: 119.99,
      imagen_url: "https://m.media-amazon.com/images/I/81prSLYZ8XL.jpg",
    },
    {
      id: 4,
      nombre: "Corsair Dominator Platinum 32GB",
      tipo_memoria: "DDR5",
      capacidad_gb: 32,
      precio: 189.99,
      imagen_url: "https://m.media-amazon.com/images/I/81prSLYZ8XL.jpg",
    },
    {
      id: 5,
      nombre: "G.Skill Trident Z5 RGB 32GB",
      tipo_memoria: "DDR5",
      capacidad_gb: 32,
      precio: 179.99,
      imagen_url: "https://m.media-amazon.com/images/I/81prSLYZ8XL.jpg",
    },
    {
      id: 6,
      nombre: "Kingston FURY Renegade 16GB",
      tipo_memoria: "DDR5",
      capacidad_gb: 16,
      precio: 129.99,
      imagen_url: "https://m.media-amazon.com/images/I/81prSLYZ8XL.jpg",
    },
  ],
  placa_madre: [
    {
      id: 1,
      nombre: "ASUS ROG Maximus Z790 Hero",
      socket: "LGA1700",
      tipo_memoria: "DDR5",
      formato: "ATX",
      precio: 629.99,
      imagen_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT4kbXRZ-3nDqCqDDTbyntJB9gGI1Tdo_qzjA&s",
    },
    {
      id: 2,
      nombre: "MSI MPG Z790 Gaming Edge WiFi",
      socket: "LGA1700",
      tipo_memoria: "DDR5",
      formato: "ATX",
      precio: 369.99,
      imagen_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT4kbXRZ-3nDqCqDDTbyntJB9gGI1Tdo_qzjA&s",
    },
    {
      id: 3,
      nombre: "Gigabyte Z790 AORUS Elite AX",
      socket: "LGA1700",
      tipo_memoria: "DDR5",
      formato: "ATX",
      precio: 329.99,
      imagen_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT4kbXRZ-3nDqCqDDTbyntJB9gGI1Tdo_qzjA&s",
    },
    {
      id: 4,
      nombre: "ASUS ROG Strix B760-I Gaming WiFi",
      socket: "LGA1700",
      tipo_memoria: "DDR5",
      formato: "Mini-ITX",
      precio: 219.99,
      imagen_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT4kbXRZ-3nDqCqDDTbyntJB9gGI1Tdo_qzjA&s",
    },
    {
      id: 5,
      nombre: "ASUS ROG Crosshair X670E Hero",
      socket: "AM5",
      tipo_memoria: "DDR5",
      formato: "ATX",
      precio: 699.99,
      imagen_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT4kbXRZ-3nDqCqDDTbyntJB9gGI1Tdo_qzjA&s",
    },
    {
      id: 6,
      nombre: "MSI MPG X670E Carbon WiFi",
      socket: "AM5",
      tipo_memoria: "DDR5",
      formato: "ATX",
      precio: 479.99,
      imagen_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT4kbXRZ-3nDqCqDDTbyntJB9gGI1Tdo_qzjA&s",
    },
    {
      id: 7,
      nombre: "Gigabyte B650 AORUS Elite AX",
      socket: "AM5",
      tipo_memoria: "DDR5",
      formato: "ATX",
      precio: 259.99,
      imagen_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT4kbXRZ-3nDqCqDDTbyntJB9gGI1Tdo_qzjA&s",
    },
    {
      id: 8,
      nombre: "ASRock B650M PG Riptide WiFi",
      socket: "AM5",
      tipo_memoria: "DDR5",
      formato: "Micro-ATX",
      precio: 189.99,
      imagen_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT4kbXRZ-3nDqCqDDTbyntJB9gGI1Tdo_qzjA&s",
    },
  ],
  almacenamiento: [
    {
      id: 1,
      nombre: "Samsung 980 PRO 1TB",
      tipo: "NVMe",
      capacidad_gb: 1000,
      precio: 149.99,
      imagen_url: "https://m.media-amazon.com/images/I/71-nZ+41uWS._AC_UF894,1000_QL80_.jpg",
    },
    {
      id: 2,
      nombre: "WD Black SN850X 2TB",
      tipo: "NVMe",
      capacidad_gb: 2000,
      precio: 229.99,
      imagen_url: "https://m.media-amazon.com/images/I/71-nZ+41uWS._AC_UF894,1000_QL80_.jpg",
    },
    {
      id: 3,
      nombre: "Crucial P3 Plus 1TB",
      tipo: "NVMe",
      capacidad_gb: 1000,
      precio: 89.99,
      imagen_url: "https://m.media-amazon.com/images/I/71-nZ+41uWS._AC_UF894,1000_QL80_.jpg",
    },
    {
      id: 4,
      nombre: "Samsung 870 EVO 1TB",
      tipo: "SSD",
      capacidad_gb: 1000,
      precio: 99.99,
      imagen_url: "https://m.media-amazon.com/images/I/71-nZ+41uWS._AC_UF894,1000_QL80_.jpg",
    },
    {
      id: 5,
      nombre: "Crucial MX500 2TB",
      tipo: "SSD",
      capacidad_gb: 2000,
      precio: 159.99,
      imagen_url: "https://m.media-amazon.com/images/I/71-nZ+41uWS._AC_UF894,1000_QL80_.jpg",
    },
    {
      id: 6,
      nombre: "Seagate Barracuda 4TB",
      tipo: "HDD",
      capacidad_gb: 4000,
      precio: 89.99,
      imagen_url: "https://m.media-amazon.com/images/I/71-nZ+41uWS._AC_UF894,1000_QL80_.jpg",
    },
    {
      id: 7,
      nombre: "WD Blue 2TB",
      tipo: "HDD",
      capacidad_gb: 2000,
      precio: 49.99,
      imagen_url: "https://m.media-amazon.com/images/I/71-nZ+41uWS._AC_UF894,1000_QL80_.jpg",
    },
  ],
  fuente: [
    {
      id: 1,
      nombre: "Corsair RM850x",
      watts: 850,
      eficiencia: "80+ Gold",
      precio: 149.99,
      imagen_url: "https://m.media-amazon.com/images/I/71Bam0yVOSS._AC_UF350,350_QL80_.jpg"
    },
    {
      id: 2,
      nombre: "EVGA SuperNOVA 1000 G6",
      watts: 1000,
      eficiencia: "80+ Gold",
      precio: 199.99,
      imagen_url: "https://m.media-amazon.com/images/I/71Bam0yVOSS._AC_UF350,350_QL80_.jpg"
    },
    {
      id: 3,
      nombre: "Seasonic PRIME TX-1000",
      watts: 1000,
      eficiencia: "80+ Titanium",
      precio: 299.99,
            imagen_url: "https://m.media-amazon.com/images/I/71Bam0yVOSS._AC_UF350,350_QL80_.jpg"
    },
    {
      id: 4,
      nombre: "be quiet! Straight Power 11 750W",
      watts: 750,
      eficiencia: "80+ Gold",
      precio: 139.99,
      imagen_url: "https://m.media-amazon.com/images/I/71Bam0yVOSS._AC_UF350,350_QL80_.jpg"
    },
    {
      id: 5,
      nombre: "Corsair SF750",
      watts: 750,
      eficiencia: "80+ Platinum",
      precio: 169.99,
      imagen_url: "https://m.media-amazon.com/images/I/71Bam0yVOSS._AC_UF350,350_QL80_.jpg"
    },
    {
      id: 6,
      nombre: "Thermaltake Toughpower GF3 1200W",
      watts: 1200,
      eficiencia: "80+ Gold",
      precio: 249.99,
      imagen_url: "https://m.media-amazon.com/images/I/71Bam0yVOSS._AC_UF350,350_QL80_.jpg"
    },
  ],
  gabinete: [
    {
      id: 1,
      nombre: "Corsair 5000D Airflow",
      formato_compatible: "ATX",
      max_gpu_mm: 400,
      precio: 174.99,
      imagen_url: "https://www.datacont.com/web/image/product.product/2419/image_1920",
    },
    {
      id: 2,
      nombre: "Lian Li O11 Dynamic EVO",
      formato_compatible: "ATX",
      max_gpu_mm: 420,
      precio: 169.99,
      imagen_url: "https://www.datacont.com/web/image/product.product/2419/image_1920",
    },
    {
      id: 3,
      nombre: "Fractal Design Meshify 2",
      formato_compatible: "ATX",
      max_gpu_mm: 467,
      precio: 159.99,
      imagen_url: "https://www.datacont.com/web/image/product.product/2419/image_1920",
    },
    {
      id: 4,
      nombre: "NZXT H7 Flow",
      formato_compatible: "ATX",
      max_gpu_mm: 400,
      precio: 129.99,
      imagen_url: "https://www.datacont.com/web/image/product.product/2419/image_1920",
    },
    {
      id: 5,
      nombre: "Cooler Master NR200P",
      formato_compatible: "Mini-ITX",
      max_gpu_mm: 330,
      precio: 99.99,
      imagen_url: "https://www.datacont.com/web/image/product.product/2419/image_1920",
    },
    {
      id: 6,
      nombre: "Lian Li A4-H2O",
      formato_compatible: "Mini-ITX",
      max_gpu_mm: 320,
      precio: 149.99,
      imagen_url: "https://www.datacont.com/web/image/product.product/2419/image_1920",
    },
    {
      id: 7,
      nombre: "Fractal Design Meshify C Mini",
      formato_compatible: "Micro-ATX",
      max_gpu_mm: 315,
      precio: 109.99,
      imagen_url: "https://www.datacont.com/web/image/product.product/2419/image_1920",
    },
  ],
  perifericos: [
    {
      id: 1,
      nombre: "LG 27GP850-B",
      tipo: "Monitor",
      especificaciones: '27" 1440p 165Hz IPS',
      precio: 399.99,
      imagen_url: "https://www.lg.com/content/dam/channel/wcms/es/images/monitores/27gp850p-b_beu_eees_es_c/450.jpg",
    },
    {
      id: 2,
      nombre: "Samsung Odyssey G7",
      tipo: "Monitor",
      especificaciones: '32" 1440p 240Hz Curved VA',
      precio: 699.99,
      imagen_url: "/placeholder.svg?height=64&width=64",
    },
    {
      id: 3,
      nombre: "Logitech G Pro X Superlight",
      tipo: "Mouse",
      especificaciones: "Inalámbrico, 63g",
      precio: 149.99,
      imagen_url: "/placeholder.svg?height=64&width=64",
    },
    {
      id: 4,
      nombre: "Razer DeathAdder V3 Pro",
      tipo: "Mouse",
      especificaciones: "Inalámbrico, 64g",
      precio: 149.99,
      imagen_url: "/placeholder.svg?height=64&width=64",
    },
    {
      id: 5,
      nombre: "Logitech G915 TKL",
      tipo: "Teclado",
      especificaciones: "Mecánico, Inalámbrico, RGB",
      precio: 229.99,
      imagen_url: "/placeholder.svg?height=64&width=64",
    },
    {
      id: 6,
      nombre: "Keychron Q1",
      tipo: "Teclado",
      especificaciones: "Mecánico, Hot-swap, RGB",
      precio: 169.99,
      imagen_url: "/placeholder.svg?height=64&width=64",
    },
    {
      id: 7,
      nombre: "SteelSeries Arctis Nova Pro",
      tipo: "Otro",
      especificaciones: "Auriculares inalámbricos",
      precio: 349.99,
      imagen_url: "/placeholder.svg?height=64&width=64",
    },
    {
      id: 8,
      nombre: "Logitech C920 HD Pro",
      tipo: "Otro",
      especificaciones: "Webcam 1080p",
      precio: 69.99,
      imagen_url: "/placeholder.svg?height=64&width=64",
    },
  ],
}
